// Re-export types from shared schemas
export type {
  Platform,
  MonitorType,
  CreateProduct,
  Product,
  UpdateProduct,
  AlertType,
  Severity,
  CreateAlert,
  Alert,
  RuleType,
  Condition,
  CreateAlertRule,
  AlertRule,
  UpdateAlertRule,
  Availability,
  PriceSnapshot,
  PriceStats,
  OpportunityRecommendation,
  OpportunityFactor,
  OpportunityAcquisitionHealth,
  BusinessMetricPriceSource,
  BusinessSignalCompleteness,
  BusinessReadiness,
  ProductBusinessSignalUpsert,
  ProductBusinessSignal,
  BusinessMetrics,
  ProductBusinessSignalResponse,
  OpportunityBusinessSummary,
  MarketSignalSnapshot,
  MarketSignalRefreshResult,
  MarketSignalProviderHealth,
  MarketSignalOpportunityFactor,
  OpportunityMarketSignalSummary,
  OpportunityResearchStatus,
  OpportunityResearchPriority,
  OpportunityResearchExportFormat,
  OpportunityResearchEntry,
  OpportunityResearchMetadata,
  OpportunityResearchUpsert,
  OpportunityResearchUpdate,
  OpportunityResearchListQuery,
  OpportunityResearchComparisonRequest,
  OpportunityResearchExportFilters,
  OpportunityResearchExportRequest,
  OpportunityResearchExportRow,
  OpportunityResearchExportResponse,
  ProductOpportunity,
  OpportunityListQuery,
  OpportunityListResponse,
  ProductOpportunityResponse,
  OpportunityResearchComparisonResponse,
  ScrapeResult,
  ScrapeAttempt,
  ScrapeJob,
  ProviderHealthResponse,
  AcquisitionQueueBackend,
  AcquisitionQueueStatus,
  AcquisitionWorkerStatus,
  AcquisitionProviderGateStatus,
  AcquisitionProviderLimitState,
  AcquisitionWorkerHeartbeat,
  AcquisitionWorkerSummary,
  AcquisitionQueueHealth,
  AcquisitionWorkerHealth,
  AcquisitionProductJobDiagnostics,
  AcquisitionJobRetryRequest,
  AcquisitionJobCancelRequest,
  AcquisitionJobControlResponse,
  AcquisitionProviderQueueStatus,
} from '@shared/schemas';

// Frontend-only types
export interface DashboardStats {
  totalProducts: number;
  monitoringProducts: number;
  unreadAlerts: number;
  totalAlerts: number;
}
