"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.providerHealthResponseSchema = exports.providerHealthAttemptSchema = exports.providerHealthSummarySchema = exports.providerHealthRecommendationSchema = exports.providerHealthQuerySchema = exports.scrapeJobSchema = exports.scrapeAttemptSchema = exports.scrapeAllResultsSchema = exports.scrapeJobReferenceSchema = exports.scrapeResultSchema = exports.acquisitionFallbackTypeSchema = exports.acquisitionRootCauseSchema = exports.acquisitionFailureReasonSchema = exports.BULK_ACQUISITION_DISABLED_CAVEAT = void 0;
const zod_1 = require("zod");
exports.BULK_ACQUISITION_DISABLED_CAVEAT =
    'Bulk monitoring acquisition is disabled by default in manual-first mode. Use POST /api/scraper/product/:productId for explicit checks or set ACQUISITION_BULK_ENABLED=true to opt in.';
// Scrape Result Schema
exports.acquisitionFailureReasonSchema = zod_1.z.enum([
    'network_timeout',
    'blocked',
    'captcha',
    'geo_restricted',
    'not_found',
    'price_missing',
    'selector_drift',
    'provider_unavailable',
    'unsupported_platform',
    'unsupported_product',
    'unsupported_url',
    'unknown',
]);
exports.acquisitionRootCauseSchema = zod_1.z.enum([
    'missing_api_key',
    'missing_credentials',
    'invalid_key',
    'auth_failed',
    'quota_exhausted',
    'rate_limited',
    'marketplace_mismatch',
    'captcha_or_blocked',
    'selector_drift',
    'cache_only',
    'insufficient_history',
    'network_timeout',
    'not_found',
    'price_missing',
    'unsupported_platform',
    'unsupported_product',
    'unsupported_url',
    'unknown',
    'insufficient_diagnostics',
]);
exports.acquisitionFallbackTypeSchema = zod_1.z.enum([
    'primary_live',
    'browser_fallback',
    'cache_fallback',
    'all_failed',
]);
exports.scrapeResultSchema = zod_1.z.object({
    success: zod_1.z.boolean(),
    productId: zod_1.z.string().optional(),
    jobId: zod_1.z.string().optional(),
    attemptId: zod_1.z.string().optional(),
    snapshotId: zod_1.z.string().optional(),
    provider: zod_1.z.string().optional(),
    source: zod_1.z.string().optional(),
    confidence: zod_1.z.number().optional(),
    data: zod_1.z.object({
        price: zod_1.z.number(),
        currency: zod_1.z.string(),
        availability: zod_1.z.string(),
        title: zod_1.z.string().optional(),
        rating: zod_1.z.number().optional(),
        reviewCount: zod_1.z.number().optional(),
        imageUrl: zod_1.z.string().optional(),
        salesRank: zod_1.z.number().optional(),
        shippingCost: zod_1.z.number().optional(),
        seller: zod_1.z.string().optional(),
        condition: zod_1.z.string().optional(),
    }).optional(),
    failureReason: exports.acquisitionFailureReasonSchema.optional(),
    diagnostics: zod_1.z.record(zod_1.z.unknown()).optional(),
    error: zod_1.z.string().optional(),
    timestamp: zod_1.z.number().optional(),
});
// Scrape All Results Schema
exports.scrapeJobReferenceSchema = zod_1.z.object({
    jobId: zod_1.z.string(),
    productId: zod_1.z.string(),
    status: zod_1.z.string(),
    created: zod_1.z.boolean(),
});
exports.scrapeAllResultsSchema = zod_1.z.object({
    enabled: zod_1.z.boolean(),
    total: zod_1.z.number(),
    queued: zod_1.z.number(),
    skipped: zod_1.z.number(),
    jobs: zod_1.z.array(exports.scrapeJobReferenceSchema),
    caveat: zod_1.z.literal(exports.BULK_ACQUISITION_DISABLED_CAVEAT).optional(),
});
exports.scrapeAttemptSchema = zod_1.z.object({
    id: zod_1.z.string(),
    jobId: zod_1.z.string().nullable().optional(),
    productId: zod_1.z.string(),
    provider: zod_1.z.string(),
    source: zod_1.z.string(),
    status: zod_1.z.string(),
    failureReason: exports.acquisitionFailureReasonSchema.nullable().optional(),
    errorMessage: zod_1.z.string().nullable().optional(),
    durationMs: zod_1.z.number(),
    confidence: zod_1.z.number().nullable().optional(),
    httpStatus: zod_1.z.number().nullable().optional(),
    pageTitle: zod_1.z.string().nullable().optional(),
    finalUrl: zod_1.z.string().nullable().optional(),
    diagnostics: zod_1.z.string().nullable().optional(),
    timestamp: zod_1.z.number(),
});
exports.scrapeJobSchema = zod_1.z.object({
    id: zod_1.z.string(),
    productId: zod_1.z.string(),
    status: zod_1.z.string(),
    priority: zod_1.z.number(),
    nextRunAt: zod_1.z.number(),
    attemptCount: zod_1.z.number(),
    maxAttempts: zod_1.z.number(),
    lastAttemptId: zod_1.z.string().nullable().optional(),
    lastFailureReason: exports.acquisitionFailureReasonSchema.nullable().optional(),
    leaseOwner: zod_1.z.string().nullable().optional(),
    leaseExpiresAt: zod_1.z.number().nullable().optional(),
    createdAt: zod_1.z.number(),
    updatedAt: zod_1.z.number(),
    completedAt: zod_1.z.number().nullable().optional(),
    metadata: zod_1.z.string().nullable().optional(),
});
exports.providerHealthQuerySchema = zod_1.z.object({
    windowHours: zod_1.z.coerce.number().int().min(1).max(24 * 30).default(24),
    productId: zod_1.z.string().optional(),
    provider: zod_1.z.string().optional(),
});
exports.providerHealthRecommendationSchema = zod_1.z.object({
    code: zod_1.z.enum([
        'configure_rainforest',
        'check_quota',
        'reduce_fallback_reliance',
        'refresh_stale_data',
        'investigate_browser_blocking',
        'configure_ebay',
        'check_ebay_credentials',
        'check_ebay_marketplace',
        'check_ebay_item_id',
        'configure_keepa',
        'check_keepa_credentials',
        'check_keepa_quota',
        'check_market_signal_identifier',
        'refresh_market_signals',
        'investigate_unknown_failures',
    ]),
    severity: zod_1.z.enum(['info', 'warning', 'critical']),
    message: zod_1.z.string(),
});
exports.providerHealthSummarySchema = zod_1.z.object({
    provider: zod_1.z.string(),
    source: zod_1.z.string(),
    attemptCount: zod_1.z.number(),
    successCount: zod_1.z.number(),
    failureCount: zod_1.z.number(),
    successRate: zod_1.z.number(),
    averageDurationMs: zod_1.z.number().nullable(),
    latestSuccessTimestamp: zod_1.z.number().nullable(),
    latestFailureReason: exports.acquisitionFailureReasonSchema.nullable(),
    latestConfidence: zod_1.z.number().nullable(),
    fallbackCount: zod_1.z.number(),
    cacheCount: zod_1.z.number(),
    failureReasons: zod_1.z.record(zod_1.z.number()),
    rootCauses: zod_1.z.record(zod_1.z.number()),
});
exports.providerHealthAttemptSchema = zod_1.z.object({
    id: zod_1.z.string(),
    productId: zod_1.z.string(),
    provider: zod_1.z.string(),
    source: zod_1.z.string(),
    status: zod_1.z.string(),
    failureReason: exports.acquisitionFailureReasonSchema.nullable(),
    durationMs: zod_1.z.number(),
    confidence: zod_1.z.number().nullable(),
    rootCause: exports.acquisitionRootCauseSchema.nullable(),
    marketplace: zod_1.z.string().nullable(),
    httpStatus: zod_1.z.number().nullable(),
    fallbackType: exports.acquisitionFallbackTypeSchema.nullable(),
    sanitizedMessage: zod_1.z.string().nullable(),
    timestamp: zod_1.z.number(),
    diagnostics: zod_1.z.record(zod_1.z.unknown()).optional(),
});
exports.providerHealthResponseSchema = zod_1.z.object({
    platform: zod_1.z.string(),
    status: zod_1.z.enum(['healthy', 'degraded', 'insufficient_history']),
    window: zod_1.z.object({
        windowHours: zod_1.z.number(),
        since: zod_1.z.number(),
        until: zod_1.z.number(),
    }),
    providerSummaries: zod_1.z.array(exports.providerHealthSummarySchema),
    chainSummary: zod_1.z.object({
        totalAttempts: zod_1.z.number(),
        liveSuccessCount: zod_1.z.number(),
        liveFailureCount: zod_1.z.number(),
        browserFallbackCount: zod_1.z.number(),
        cacheFallbackCount: zod_1.z.number(),
        primaryFailureCount: zod_1.z.number(),
        degradedPathCounts: zod_1.z.record(zod_1.z.number()),
        rootCauses: zod_1.z.record(zod_1.z.number()),
    }),
    latestAttempts: zod_1.z.array(exports.providerHealthAttemptSchema),
    recommendations: zod_1.z.array(exports.providerHealthRecommendationSchema),
});
